# Generated by Django 4.2.7 on 2023-11-27 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='picture',
            field=models.ImageField(default='img/default_chat.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='chat',
            name='private_links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='online',
            field=models.ManyToManyField(blank=True, related_name='online_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chat',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
