# Generated by Django 4.2.7 on 2023-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_online_alter_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group_name',
            field=models.CharField(default=str, max_length=64),
        ),
    ]
