# Generated by Django 4.2.7 on 2023-11-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='online',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='private_links',
        ),
        migrations.AddField(
            model_name='chat',
            name='private_link',
            field=models.JSONField(default=dict),
        ),
    ]
