# Generated by Django 4.2.7 on 2023-12-06 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_chatadmin_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatadmin',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
        migrations.AddField(
            model_name='chatadmin',
            name='user',
            field=models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(related_name='owned_chats', through='chat.ChatAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chats', through='chat.ChatUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
